name: CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode_14.0.app/Contents/Developer
    
    - name: Update Secrets
      run: sed -i -e 's/APIKey = ""/APIKey = "${{ secrets.API_KEY }}"/g' CinemaTime/Secrets/Secrets.swift
    
    - name: Build and test
      run: |
        xcodebuild clean build test -project CinemaTime.xcodeproj -scheme "CI" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk macosx -destination "platform=macOS" ONLY_ACTIVE_ARCH=YES
